---

version: 2
updates:

#
# Maintain dependencies for GitHub Actions
#

- package-ecosystem: github-actions
  open-pull-requests-limit: 5
  directory: "/" # Workflow files stored in the default location of '.github/workflows'. (You don't need to specify '/.github/workflows' for 'directory'. You can use 'directory: "/"'.)
