# These are supported funding model platforms

# List up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
github:
  # - norwd

# List up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
custom:
  - 'https://crisisrelief.un.org/ukraine-crisis'
