---

prerelease: true

name-template: 'v$RESOLVED_VERSION 📦🚀📄'
tag-template: 'v$RESOLVED_VERSION'

change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'

categories:
  - title: '🚀 Features'
    collapse-after: 3
    labels:
      - 'feature'
      - 'enhancement'

  - title: '🐛 Bug Fixes'
    collapse-after: 3
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

  - title: '🧰 Maintenance'
    collapse-after: 3
    labels:
      - 'chore'
      - 'github'
      - 'documentation'
      - 'doc'
      - 'docs'

  - title: '⬆️ Dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'
      - 'deps'

version-resolver:
  default: patch

  major:
    labels:
      - 'major'

  minor:
    labels:
      - 'minor'

  patch:
    labels:
      - 'patch'

template: |
  ## Changes

  $CHANGES

  ## Thanks

  $CONTRIBUTORS
