#
# SPDX-FileCopyrightText: 2026 Y. Meyer-Norwood <norwd@noreply.codeberg.org>
# SPDX-License-Identifier: LicenseRef-Hippocratic-3.0-CL-ECO-LAW-MIL-SV
#

---

name: "Run Linters"
on: push
concurrency:
  group: ${{ forgejo.workflow_ref }}
  cancel-in-progress: true

jobs:
  linters:
    name: "Run Linters"
    runs-on: codeberg-small-lazy
    timeout-minutes: 10
    steps:

      - name: "Install Dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y reuse

          # v3.6.1 is the last slop-free release of editorconfig-checker
          curl -fsSLo- "https://github.com/editorconfig-checker/editorconfig-checker/releases/download/v3.6.1/editorconfig-checker-linux-amd64.tar.gz" | sudo tar xvz -C /usr/bin editorconfig-checker

          # v3.90.12 is the last slop-free release of trufflehog
          curl -fsSLo- "https://github.com/trufflesecurity/trufflehog/releases/download/v3.90.12/trufflehog_3.90.12_linux_amd64.tar.gz" | sudo tar xvz -C /usr/bin trufflehog

      - name: "Checkout (for linting)"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Run Linters"
        run: |
          reuse lint
          editorconfig-checker --verbose
          trufflehog git file://. --results="verified,unknown" --concurrency="$(nproc)" --no-update --fail

...
