---

name: "Debug Workflow Run"
run-name: "Debug Workflow Run"
permissions: read-all

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
  push:
    paths: ['.github/workflows/debug.yml']
  schedule:
    - cron: '0 0 * * 0'

env:
  GH_TOKEN: ${{ github.token }}

jobs:

  debug:
    runs-on: ubuntu-slim
    steps:
      - run: true
