---

name: "Debug Workflow Run"
run-name: "Debug Workflow Run"
permissions: read-all

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
  push:
    paths: ['.github/workflows/debug.yml']
  schedule:
    - cron: '0 0 * * 0'

env:
  GH_TOKEN: ${{ github.token }}

jobs:

  debug-matrix-includes:
    runs-on: ubuntu-slim
    strategy:
      matrix:
        foo: [a,b,c]
        bar: [x,y,z]
        include:
          - baz: 1
          - baz: 2
          - baz: 3
    steps:
      - run: echo "${JSON}" | jq '.'
        env:
          JSON: ${{ toJson(matrix) }}
