---

name: "Enable Automerge"
run-name: "Automerge enabled for #${{ github.event.number }}"
permissions: read-all

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: alexwilson/enable-github-automerge-action@1.0.0
        with:
          github-token: ${{ secrets.AUTO_MERGE_NORWD || secrets.GITHUB_TOKEN }}
