#
# SPDX-FileCopyrightText: 2026 Y. Meyer-Norwood <norwd@noreply.codeberg.org>
# SPDX-License-Identifier: LicenseRef-Hippocratic-3.0-CL-ECO-LAW-MIL-SV
#

---

name: "Follow Users"
run-name: "Following Users"
permissions: {}

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push: {paths: [.github/workflows/follow.yml]}
  schedule:
    - cron: "0 0 * * *"

env:
  GH_TOKEN: ${{ secrets.FOLLOW_USERS_NORWD }}
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  follow-all-members-of-my-repos:
    name: "Follow all members of my repos"
    runs-on: ubuntu-latest
    steps:

      - name: "List orgs"
        run: gh api "${ENDPOINT}" --jq "${JQ_QUERY}" | tee -a orgs.txt
        env:
          ENDPOINT: user/orgs
          JQ_QUERY: .[].url

      - name: "List members"
        run: xargs -IORG_BASE_URL gh api "${ENDPOINT}" --jq "${JQ_QUERY}" < orgs.txt | tee -a users.txt
        env:
          ENDPOINT: ORG_BASE_URL/members
          JQ_QUERY: .[].login

      - name: "Follow all members of my repos"
        run: sort --unique < users.txt | xargs -IUSERNAME gh api --method PUT "${ENDPOINT}"
        env:
          ENDPOINT: /user/following/USERNAME
