---

name: "Setting Bio to Random Fortune"
run-name: "Setting Bio to ${{ inputs.fortune || 'Random Fortune' }}"
permissions: {}

concurrency:
  group: fortune
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on:
  schedule:
    - cron: "0 * * * *"

  push:
    branches: main
    paths:
      - fortunes.json
      - .github/workflows/fortune.yml

  workflow_dispatch:
    inputs:
      fortune:
        description: "Specific fortune to use, if unset, a random fortune will be used."
        required: false
        type: string

env:
  GH_TOKEN: ${{ secrets.BIO_UPDATE_NORWD }}
  FORTUNE: ${{ inputs.fortune }}

jobs:
  set-bio:
    name: "Set bio"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Select Random Fortune"
        if: inputs.fortune == ''
        run: |
          EOF_MARKER="$(head -c 8 /dev/random | hexdump -v -e '1/1 \"%.2X\"')"
          echo "::add-mask::${EOF_MARKER}"
          echo "FORTUNE<<${EOF_MARKER}" >> "${GITHUB_ENV}"
          jq -r '.[]' < fortunes.json | sort --random-sort | head -1 | tee -a "${GITHUB_ENV}"
          echo "${EOF_MARKER}" >> "${GITHUB_ENV}"

      - name: "Install gh-user"
        run: gh extension install norwd/gh-user

      - name: "Set Bio"
        run: gh user bio "${FORTUNE}"
