---

name: "Keep Repo Active"
run-name: "Keep Repo Active"
permissions: {}

concurrency:
  group: heartbeat
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push: {paths: [.github/workflows/heartbeat.yml]}
  schedule:
    - cron: "30 1 * * *"

jobs:
  keep-repo-active:
    name: "Keep Repo Active"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.README_UPDATE_NORWD }}
          ref: ${{ github.ref }}

      - name: Setup GPG Keys
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.AUTO_COMMIT_GPG_PRIVATE_KEY_NORWD }}
          passphrase: ${{ secrets.AUTO_COMMIT_GPG_PASSPHRASE_NORWD }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: .
          commit_author: norwd <106889957+norwd@users.noreply.github.com>
          commit_user_name: norwd
          commit_user_email: 106889957+norwd@users.noreply.github.com
          commit_message: Keep repo alive
          commit_options: --allow-empty -s -S
