---

name: "Pull Request Labeler"
run-name: "Assigning labels for #${{ github.event.number }}"
permissions: read-all

on:
  - pull_request_target

jobs:
  label:
    permissions:
      pull-requests:
        write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.AUTO_LABEL_NORWD || secrets.GITHUB_TOKEN }}"
          sync-labels: true
