---

name: "Manage Notifications"
run-name: "Manage Notifications"
permissions: {}

concurrency:
  group: manage-notifications
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push: {paths: [.github/notifications/.yml]}
  schedule:
    - cron: "*/6 * * * *" # run every 6 minutes, max frequency is every 5, this means this is out of phase with everyone who just spams every 5min

env:
  GH_TOKEN: ${{ secrets.MANAGE_NOTIFICATIONS_NORWD }}

jobs:
  delete-notifications:
    name: "Mark Notifications as Done"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - subject_title_regex: "^Publish (v[0-9]+.[0-9])|candidate" # Ignore release or release candidate PRs

    steps:
      - name: "Mark Notifications as Done"
        run: gh api /notifications --jq "${JQ_QUERY}" | xargs -ITHREAD gh api -X DELETE THREAD
        env:
          JQ_QUERY: '.[] | select(.subject.title | test("${{ matrix.subject_title_regex }}"; "i")) | .url'
