---

name: "Regenerating README"
run-name: "Regenerating README"
permissions: {}

concurrency:
  group: profile
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on:
  push:
    paths:
      - .github/workflows/profile.yml
      - fortunes.json

jobs:
  generate-readme:
    name: "Generate README"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.README_UPDATE_NORWD }}
          ref: ${{ github.ref }}

      - name: Replace Patterns in Template
        run: |
          cat << EOF > README.md
          <!-- markdownlint-disable -->

          <!-- WARNING! ANY CHANGES MADE HERE WILL BE LOST -->

          \`\`\`csharp
          /// <summary>
          /// Hi, I'm <see cref="norwd" />.
          /// </summary>
          public class norwd
          {
            /// <summary>
            /// My <see cref="norwd.Pronouns" /> are he/him/his.
            /// </summary>
            public const Pronoun Pronouns = Pronoun.He | Pronoun.Him | Pronoun.His;

            /// <summary>
            /// Some of my external links.
            /// </summary>
            public IDictionary<string, Uri> Links => new Dictionary<string, Uri>
            {
              ["GitHub"]        = new Uri("https://github.com/norwd"),
              ["JiraStopWatch"] = new Uri("https://jirastopwatch.github.io"),
            };

            /// <summary>
            /// Get a randomised fortune each time.
            /// </summary>
            /// <remarks>
            /// These fortunes are periodically set as my bio!
            /// </remarks>
            public string Fortune => new[]
            {
          $(jq '.[]' < fortunes.json | sed 's/^/    /g' | sed 's/$/,/g')
            }
            .OrderBy(_ => new Random().Next())
            .First();
          }
          \`\`\`

          All of my code is 100% Human-Made, either writen by me or generated by a utiliy that was.

          <img src="https://humanmademark.com/automatic-logo.svg" height="50" />

          EOF

      - name: Setup GPG Keys
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.AUTO_COMMIT_GPG_PRIVATE_KEY_NORWD }}
          passphrase: ${{ secrets.AUTO_COMMIT_GPG_PASSPHRASE_NORWD }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: README.md
          commit_author: norwd <106889957+norwd@users.noreply.github.com>
          commit_user_name: norwd
          commit_user_email: 106889957+norwd@users.noreply.github.com
          commit_message: Auto generate README.md
          commit_options: -s -S
