---

name: "Regenerating README"
run-name: "Regenerating README"
permissions: {}

concurrency:
  group: profile
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on:
  push:
    paths:
      - .github/workflows/profile.yml
      - fortunes.json

jobs:
  generate-readme:
    name: "Generate README"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.README_UPDATE_NORWD }}
          ref: ${{ github.ref }}

      - name: Replace Patterns in Template
        run: |
          cat << EOF > README.md
          <!-- markdownlint-disable -->

          <!-- WARNING! ANY CHANGES MADE HERE WILL BE LOST -->

          # I'm Using GitHub Under Protest

          Many of my projects are currently hosted on GitHub.
          This is not ideal; GitHub is a proprietary, trade-secret system that is not Free and Open Source Software (FOSS).
          I am deeply concerned about using a proprietary system like GitHub to develop my FOSS projects.
          I have an [open discussion][Leaving GitHub Discussion] where I am keeping track of moving my projects away from GitHub and to [CodeBerg].
          I urge you to read about the [Give up GitHub] campaign from the [Software Freedom Conservancy] to understand some of the reasons why GitHub is not a good place to host FOSS projects.

          If you are a contributor who personally has already quit using GitHub, please [check this resource][Leaving GitHub Discussion] for how to send in contributions without using GitHub directly.

          Any use of my projects' code by GitHub Copilot, past or present, is done without my permission.
          I do not consent to GitHub's use of any of my projects' code in Copilot.

          ![Logo of the GiveUpGitHub campaign](https://sfconservancy.org/static/img/GiveUpGitHub.png)

          [Leaving GitHub Discussion]: https://github.com/norwd/norwd/discussions/7
          [Give up GitHub]: https://GiveUpGitHub.org
          [Software Freedom Conservancy]: https://sfconservancy.org
          [Codeberg]: https://codeberg.org/norwd
          EOF

      - name: Setup GPG Keys
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.AUTO_COMMIT_GPG_PRIVATE_KEY_NORWD }}
          passphrase: ${{ secrets.AUTO_COMMIT_GPG_PASSPHRASE_NORWD }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: README.md
          commit_author: norwd <106889957+norwd@users.noreply.github.com>
          commit_user_name: norwd
          commit_user_email: 106889957+norwd@users.noreply.github.com
          commit_message: Auto generate README.md
          commit_options: -s -S
