---

name: "Syncing Forks"
run-name: "Syncing Forks"
permissions: {}

concurrency:
  group: sync-forks
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push: {paths: [.github/workflows/sync.yml]}
  schedule:
    - cron: "0 * * * *"

env:
  GH_TOKEN: ${{ secrets.SYNC_FORKS_NORWD }}

jobs:
  sync:
    name: "Sync Forks"
    runs-on: ubuntu-latest
    steps:
      - name: "Install Utils"
        run: |
          git clone https://github.com/norwd/snore
          cd snore
          sudo make clean install
          cd ..
          rm -rf snore

      - name: "Sync Forks"
        run: gh repo list "${REPO_OWNER}" --fork --no-archived --limit 1000 --json nameWithOwner --template "${TEMPLATE}" | sh -v
        env:
          REPO_OWNER: '${{ github.repository_owner }}'
          TEMPLATE: |
            {{range .}}
            gh repo sync {{.nameWithOwner}}
            {{"\n"}}
            snore 1m
            {{"\n"}}
            {{end}}
