---

name: "Syncing Forks"
run-name: "Syncing Forks"
permissions: {}

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push: {paths: [.github/workflows/sync.yml]}
  schedule:
    - cron: "0 * * * *" # note, also update SECONDS_BETWEEN_RUNS if you change this

env:
  GH_TOKEN: ${{ secrets.SYNC_FORKS_NORWD }}
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  list:
    name: "List ${{ matrix.fork }}"
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.list.outputs.json }}
    steps:
      - id: list
        name: "List Forks"
        run: gh repo list "${REPO_OWNER}" --fork --no-archived --limit 1000 --json "${JQ_PROPS}" --jq "${JQ_QUERY}" | sort --random-sort | jq --slurp --raw-output '"json=" + (. | tostring)' | tee -a "${GITHUB_OUTPUT}"
        env:
          JQ_PROPS: 'nameWithOwner,parent,pushedAt'
          JQ_QUERY: 'sort_by(.pushedAt)[:256][] | ({ fork: .nameWithOwner, source: (.parent.owner.login + "/" + .parent.name) } | tostring)'

  sync:
    name: "Sync Forks"
    runs-on: ubuntu-latest
    needs: list
    timeout-minutes: 120

    concurrency:
      group: sync-forks-${{ join(matrix.*, '-') }}
      cancel-in-progress: false

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include: ${{ fromJSON(needs.list.outputs.json) }}

    env:
      FORK: ${{ matrix.fork }}
      SOURCE: ${{ matrix.source }}

    steps:
      - id: delay
        name: "Pick delay"
        run: gh api "${ENDPOINT}" --jq "${JQ_QUERY}" | tee -a "${GITHUB_OUTPUT}"
        env:
          ENDPOINT: '/rate_limit'
          JQ_QUERY: '"seconds=" + ( [ .resources[] | select(.used != 0) | ( (.used / .limit) * (.reset - ( now | tonumber | floor ) | abs) ) ] + [0] | max | ceil | tostring)'

      - name: "Wait ${{ steps.delay.outputs.seconds }} Seconds" # wait a bit to prevent rate limiting with so many other jobs going
        run: sleep "${SECONDS}"
        env:
          SECONDS: ${{ steps.delay.outputs.seconds }}

      - name: "Sync ${{ matrix.fork }} from ${{ matrix.source }}"
        run: gh repo sync "${FORK}" --source "${SOURCE}"
