---

name: "Syncing Forks"
run-name: "Syncing Forks"
permissions: {}

concurrency:
  group: sync-forks
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push: {paths: [.github/workflows/sync.yml]}
  schedule:
    - cron: "0 * * * *"

env:
  GH_TOKEN: ${{ secrets.SYNC_FORKS_NORWD }}

jobs:
  sync:
    name: "Sync Forks"
    runs-on: ubuntu-latest
    steps:
      - name: "Sync Forks"
        run: gh repo list "${REPO_OWNER}" --fork --no-archived --limit 1000 --json nameWithOwner --jq "${JQ_QUERY}" | sort --unique --random-sort | head -n 10 | xargs -IREPO sh -c "${SH_XARGS}"
        env:
          REPO_OWNER: '${{ github.repository_owner }}'
          JQ_QUERY: '.[].nameWithOwner'
          SH_XARGS: |
            echo "::group::Syncing REPO..."
            gh repo sync REPO
            sleep 10
            echo "::endgroup::"
