---

name: "Syncing Forks"
run-name: "Syncing Forks"
permissions: {}

concurrency:
  group: sync-forks
  cancel-in-progress: false

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push: {paths: [.github/workflows/sync.yml]}
  schedule:
    - cron: "0 * * * *"

env:
  GH_TOKEN: ${{ secrets.SYNC_FORKS_NORWD }}

jobs:
  sync:
    name: "Sync Forks"
    runs-on: ubuntu-latest
    steps:
      - name: "Sync Forks"
        run: gh repo list "${REPO_OWNER}" --fork --no-archived --limit 1000 --json "${JQ_PROPS}" --template "${TEMPLATE}" | sort --unique --random-sort | sh -v
        env:
          REPO_OWNER: '${{ github.repository_owner }}'
          JQ_PROPS: 'nameWithOwner'
          TEMPLATE: |
            {{range .}}
            gh repo sync {{.nameWithOwner}} && sleep 60;{{"\n"}}
            {{end}}
